sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 2mjcnh3FgnaQ3AwwEmBIt/EJw5j9ly1LuOp78RDJ5QduZKNLingxZJP8tak8kV0FoXQh1+EVEOHfUnKq/UZNh86C3B7znIPYgtIT5KYsSgDrijBLBgR4yrIKGug/ZU8vdJYrQG78RXdTgA5HLVTlxW0ZdkjX1AGjPqcTr84HIZgG98W0JaAyBo8YECQ1H6i22Y2+n6sdf+aFTT3R1bTyuB2DUcHDTeUUAQRZs07z4OMmQWZ+SIpEqGr7q+kZsQuqdG5naOUt4DJih0JWr63lO3QgPUzgzSLuV1VRtbVeiZeMS1Ps90dfn0g8IYZm5xfM0I62Uumys8TlU8oD4eEJUu8LUfhDzDjbd9sxNVVTOMiq9LA3ykPh5llHOsCEDHD1SsXZ4SWBFCq9MNVws2Ki8thsZewC+CYti2peGyAPzKlJtlFomJM5Z5Tf7s+WguxOZhCNFiXHw1B/Am03PYSTW4jqCgz3DBvWJnsoUfMd+Yox1Vj9uHGSZJ7ZPLMZi2pnCd6NuaN9N187NwEmbbh9D2kGUwpSKK8Aq6jR5TOWmWOJrrH6FjX9I0jqnk8Zw3y4KxP2XLh8dotPDr6Qlg7uQ/r3NFVKL3Qk0Qv2iiKU/H9n8N7Vs0I+sBuc96nbxmdkx6x9inrl7b9LFGigrlbRvmK39I6PtwYMePIaOT9tTf4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Roman-and-the-Teuton--13-A-Series-of-Lectures-delivered-before-the-University-of-Cambridge_3821
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy